import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Sidenavbar from "../Components/Sidenavbar.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Trial and Error",
  description: "Generated by me",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen">
          <div className="w-1/6">
            <Sidenavbar />
          </div>

          <div className="w-5/6 p-6 bg-gray-100 overflow-y-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
